FUNCTION RECURSIVE

In [1]:
def faktorial(n):
    if n == 0:
        return 0
    
    print(n)
    faktorial(n-1)

faktorial(5)


5
4
3
2
1


In [4]:
def test(n):
    if n == 0:
        return True
    else :
        print(n)
        return n * test(n - 1)

test(5)

5
4
3
2
1


120

In [5]:
def test(n):
    if n == 0:
        return False
    else :
        print(n)
        return n * test(n - 1)

test(5)

5
4
3
2
1


0

ASSIGNMENT

In [6]:
# 2

data = [10, 20, 30, 40, 50]

print(min(data))
print(max(data))

10
50


FUNCTION ARGS & KWARGS

In [ ]:
def tampil(*a): # ARGS
    print(a)

tampil("satu", "dua", "tiga")

('satu', 'dua', 'tiga')


In [9]:
def tampil(*a):
    print(a)
    print(a[0])
    print(a[1])
    print(a[2])

tampil("satu", "dua", "tiga")

('satu', 'dua', 'tiga')
satu
dua
tiga


In [ ]:
def tampil(*a): # kombinasi ARGS + Looping
    print(a)
    for i in a:
        print(i)

tampil("satu", "dua", "tiga")

('satu', 'dua', 'tiga')
satu
dua
tiga


In [13]:
def tampil2(**a): # KWARGS
    print(a)

tampil2(nama="william", alamat="surabaya")

{'nama': 'william', 'alamat': 'surabaya'}


In [14]:
def tampil2(**a): # KWARGS + Looping
    print(a)
    for key in a.keys():
        print(a[key])

tampil2(nama="william", alamat="surabaya")

{'nama': 'william', 'alamat': 'surabaya'}
william
surabaya


NUMPY

In [ ]:
import numpy as np

a = np.array([1,2,3,4]) # 1 dimensi
print(a)
print(a[0])
print(a[1])

[1 2 3 4]
1
2


In [19]:
b = np.array([ # 2 dimensi
    [1,2,3],
    [4,5,6],
    [7,8,9],
])

print(b)
print(b[0])
print(b[1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[4 5 6]


In [ ]:
b = np.array([ 
    [1,2,3],
    [4,5,6],
    [7,8,9],
])

print(b)
print(b[0])
print(b[0] [2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
3


In [24]:
c = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])

print(c)
print(c[0])
print(c[0][0])
print(c[0][0][2])



[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[1 2 3]
 [4 5 6]]
[1 2 3]
3


In [ ]:
b = np.array([ # 2 dimensi
    [1,2,3],
    [4,5,6],
    [7,8,9],
])

print(b.shape)
print(b.ndim)
print(b.size)

(3, 3)
2
9


ASSIGNMENT

In [26]:
b = np.array([ # 2 dimensi
    [10,20,30],
    [5,10,20],
    [2,4,6],
])

print(b)


[[10 20 30]
 [ 5 10 20]
 [ 2  4  6]]


In [27]:
c = np.array([
    [
        [10,11,12],
        [13,14,15],
        [16,17,18]
    ],
    [
        [20,21,22],
        [23,24,25],
        [26,27,28]
    ],
    [
        [30,31,32],
        [33,34,35],
        [36,37,38]
    ]
])

print(c)


[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[20 21 22]
  [23 24 25]
  [26 27 28]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]]]


In [31]:
c = np.array([
    [
        ["MacBook",3,"25JT"],
        ["Asus",15,"11JT"],
        ["HP",6,"8JT"]
    ],
    [
        ["Iphone",5,"13JT"],
        ["Oppo",22,"5JT"],
        ["Vivo",8,"4JT"]
    ]
])

print(c)
print(c.shape)
print(c.ndim)

[[['MacBook' '3' '25JT']
  ['Asus' '15' '11JT']
  ['HP' '6' '8JT']]

 [['Iphone' '5' '13JT']
  ['Oppo' '22' '5JT']
  ['Vivo' '8' '4JT']]]
(2, 3, 3)
3


In [33]:
b = np.array([ 
    ["Raka",21,"Badung","Programmer"],
    ["Bayu",22,"Denpasar","Web Developer"],
    ["Sri",18,"Gianyar","Android Developer"],
    ["Dimas",30,"Bangli","Data Analyst"]
])

print(b)
print(b.shape)
print(b.size)

[['Raka' '21' 'Badung' 'Programmer']
 ['Bayu' '22' 'Denpasar' 'Web Developer']
 ['Sri' '18' 'Gianyar' 'Android Developer']
 ['Dimas' '30' 'Bangli' 'Data Analyst']]
(4, 4)
16


INDEXING & SLICING

In [42]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(a[0])
print(a[0:])


[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(a[0:, 0:2])
print(a[1:, 0:2])



[[1 2]
 [4 5]
 [7 8]]
[[4 5]
 [7 8]]


In [46]:
a[0] = 20
print(a[0:])

[[20 20 20]
 [ 4  5  6]
 [ 7  8  9]]


In [49]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

a[0][1] = 20
print(a[0:])

[[ 1 20  3]
 [ 4  5  6]
 [ 7  8  9]]


In [50]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

a[0][1] = 20
print(a[0])

[ 1 20  3]


In [51]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

a[0][1] = 20
print(a[0:, 0:2])

[[ 1 20]
 [ 4  5]
 [ 7  8]]


ASSIGNMENT

In [53]:
a = np.array([ 
    ["Denis","Scratch",8],
    ["Frank","Python",18],
    ["Roger","Unity",15]
])

print(a[0])
print(a[1])
print(a[2]) 

['Denis' 'Scratch' '8']
['Frank' 'Python' '18']
['Roger' 'Unity' '15']


In [60]:
a = np.array([ 
    ["Denis","Scratch",8],
    ["Frank","Python",18],
    ["Roger","Unity",15]
])

print(a[0:, 0])
print(a[0:, 1])

['Denis' 'Frank' 'Roger']
['Scratch' 'Python' 'Unity']


In [62]:
a = np.array([ 
    ["Denis","Scratch",8],
    ["Frank","Python",18],
    ["Roger","Unity",15]
])

a[0][1] = "Roblox"
print(a[0:])

[['Denis' 'Roblox' '8']
 ['Frank' 'Python' '18']
 ['Roger' 'Unity' '15']]


In [63]:
a = np.array([ 
    ["Java","Richie",60,"C"],
    ["Python","Niels",80,"A"],
    ["R","Brie",75,"B"]
])

print(a)

[['Java' 'Richie' '60' 'C']
 ['Python' 'Niels' '80' 'A']
 ['R' 'Brie' '75' 'B']]


In [65]:
a = np.array([ 
    ["Java","Richie",60,"C"],
    ["Python","Niels",80,"A"],
    ["R","Brie",75,"B"]
])

print(a[0:, 0])
print(a[0:, 1])
print(a[0:, 2])

['Java' 'Python' 'R']
['Richie' 'Niels' 'Brie']
['60' '80' '75']


In [66]:
a = np.array([ 
    ["Java","Richie",60,"C"],
    ["Python","Niels",80,"A"],
    ["R","Brie",75,"B"]
])

print(a[0:, 0])
print(a[0:, 1])
print(a[0:, 2])
print(a[0:, 3])

['Java' 'Python' 'R']
['Richie' 'Niels' 'Brie']
['60' '80' '75']
['C' 'A' 'B']


In [69]:
a = np.array([ 
    ["Java","Richie",60,"C"],
    ["Python","Niels",80,"A"],
    ["R","Brie",75,"B"]
])

print(a[0:2, 2:])


[['60' 'C']
 ['80' 'A']]


In [ ]:
a = np.array([ 
    ["Java","Richie",60,"C"],
    ["Python","Niels",80,"A"],
    ["R","Brie",75,"B"]
])

a[0:, 0] = "Data Analyst"
print(a)

[['Data Analyst' 'Richie' '60' 'C']
 ['Data Analyst' 'Niels' '80' 'A']
 ['Data Analyst' 'Brie' '75' 'B']]


In [71]:
a = np.array([ 
    ["Java","Richie",60,"C"],
    ["Python","Niels",80,"A"],
    ["R","Brie",75,"B"]
])

a[2][2] = "90"
a[2][3] = "A+"
print(a[0:])

[['Java' 'Richie' '60' 'C']
 ['Python' 'Niels' '80' 'A']
 ['R' 'Brie' '90' 'A+']]
